### ISSUE TITLE
Problem with m2node (?)

### ISSUE THREAD

**Issue by nikosst** [OPENi-ict/openi-auth-dialogs#1]
• Cant POST to /auth/login (and most probably to all other paths)
• Getting the following error:
Error: stream.push() after EOF
          Error: stream.push() after EOF
                 at readableAddChunk (_stream_readable.js:146:15)
                 at IncomingMessage.Readable.push (_stream_readable.js:127:10)
                 at HTTPParser.parserOnBody [as onBody](http.js:142:22)
                 at FakeSocket.socket.ondata (http.js:1966:22)
                 at FakeSocket.emitData (/home/openi/openi/repos/openi-auth-dialogs/node_modules/m2node/lib/m2node/fake_socket.js:31:21)
                 at Handler.<anonymous> (/home/openi/openi/repos/openi-auth-dialogs/node_modules/m2node/lib/m2node.js:21:25)
                 at Handler.EventEmitter.emit (events.js:95:17)
                 at Socket.<anonymous> (/home/openi/openi/repos/openi-auth-dialogs/node_modules/m2node/lib/m2node/handler.js:20:24)
                 at Socket.EventEmitter.emit (events.js:95:17)
                 at Object._onImmediate (/home/openi/openi/repos/openi-auth-dialogs/node_modules/m2node/node_modules/zmq/lib/index.js:358:25)

It’s probably an issue with m2node module

**Comment by dmccarthy-dev** [comment]
Are you sending the permissions as a base64 encoded parameter? I've seen this error if the URL is too long.

**Comment by dmccarthy-dev** [comment]
we are working on persisting the permissions through the admin dialog right now.

**Comment by nikosst** [comment]
the GET @auth/account that has the url parameter with base64 permissions works fine. The problem is at the specific POST. the body of the POST is simple/small, just a json {username:"", password:""}

**Comment by dmccarthy-dev** [comment]
@nikosst, I cannot recreate this bug locally. It may be the case that this bug (https://github.com/OPENi-ict/auth-api/issues/1) that I fixed earlier was also causing this issue. Can you confirm this?

**Comment by nikosst** [comment]
aaaah, updated nodejs and problem solved.... :\ (v0.10.33)
It hadn't to do with auth-api
