### ISSUE TITLE
Error crashing server

### ISSUE THREAD

**Issue by dmccarthy-dev** [OPENi-ict/openi-auth-dialogs#2]
/home/ubuntu/repos/openi-auth-dialogs/routes/login.js:28
         if (deepEqual(resp_data, req.session.appPerms["permissions"])) {
                                                      ^
TypeError: Cannot read property 'permissions' of undefined
    at /home/ubuntu/repos/openi-auth-dialogs/routes/login.js:28:55
    at IncomingMessage.<anonymous> (/home/ubuntu/repos/openi-auth-dialogs/routes/postScript.js:43:10)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)

**Comment by dmccarthy-dev** [comment]
Code now checks that the apps permissions have been set before proceeding.
