### ISSUE TITLE
appPerms in req.session.appPerms not defined 

### ISSUE THREAD

**Issue by dmccarthy-dev** [OPENi-ict/openi-auth-dialogs#3]
/home/ubuntu/repos/openi-auth-dialogs/routes/account.js:83
                        if (req.session.appPerms.hasOwnProperty("permissions")
                                                 ^
TypeError: Cannot call method 'hasOwnProperty' of undefined
    at /home/ubuntu/repos/openi-auth-dialogs/routes/account.js:83:50
    at IncomingMessage.<anonymous> (/home/ubuntu/repos/openi-auth-dialogs/routes/postScript.js:43:10)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16

**Comment by dmccarthy-dev** [comment]
Added check to see if req.session.appPerms is undefined and returns an error page if it is.
